### ISSUE TITLE
Could you support LDAP login and auto create user？

### ISSUE THREAD

**Issue by jollychang** [etsy/mixer#2]
Could you support LDAP login and auto create user？and provide a new user form?

**Comment by bgreenlee** [comment]
That's a good idea. We don't have a need for that internally, so it's not going to be a high priority unless there's a lot of demand for it, but we we're happy to consider any pull requests.

**Comment by jgoulah** [comment]
LDAP login is a different system that is decoupled from this app.  Your authentication system should pass the X-Username header into the app to pre-populate the new user form (which exists already) but there is currently no login system built or plans to do so.  Please re-open this if you would like to contribute a patch.
